cc_binary (
    name = 'io_watcher',
    srcs = 'io_watcher.cpp',
    deps = [
        '//thirdparty/libev:ev',
    ]
)

cc_binary (
    name = 'http_server',
    srcs = 'http_server.cpp',
    deps = [
        '//thirdparty/libev:ev',
    ]
)
